### PR TITLE
Add option to reply to all messages and implement /dalle command

### PR DESCRIPTION
**Pull request by znadir**
Hi @matiasvlevi,

I've made some updates to the discord bot. Specifically, I've added an option in the .env file that allows the bot to listen and reply to all messages sent in the server. Also, I've implemented the /dalle command which generates an image from a prompt using DALL-E.

Since the bot support image generation, you should now change the repository name for something more generic like "OpenAI-discord-bot"

That's it!
Thanks for considering my pull requests

### CODE REVIEW

**Review by matiasvlevi — CHANGES_REQUESTED** [review]
Response length 0 should result in the bot replying "..."

**Comment by znadir** [comment]
Well I don't think DALLE can return an empty image URL. It may return an http error though. That's why I didn't put the Response length 0 check. I have attached a screenshot of what would happen if there is an http error

image

**Comment by matiasvlevi** [comment]
> Well I don't think DALLE can return an empty image URL. It may return an http error though. That's why I didn't put the Response length 0 check. I have attached a screenshot of what would happen if there is an http error
> 
> image
> 

Line 21 in `events/MessageCreate.js` currently replies `I dont know what to say :(`.

Should reply `...`

Not related to DALLE at all.

**Comment by znadir** [comment]
Done

**Pull request merged**
